{% set name = "javascripthon" %}
{% set version = "0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16077e073721507dbea175465cf52b30b7bb16a178a346b5834ae41d95463ad9
  patches:
    - py38.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pj = metapensiero.pj.__main__:main

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - dukpy
    - macropy3 >=1.1.0b2

test:
  imports:
    - metapensiero.pj
  commands:
    - pj --help

about:
  home: https://gitlab.com/metapensiero/metapensiero.pj
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Javascript for refined palates: a Python 3 to ES6 Javascript translator.'

extra:
  recipe-maintainers:
    - hoechenberger
