{% set name = "javascripthon" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aef945c3c544f3c527b6497a01a3e057d2049b9a2f660f99ad0cf1da7995bfdb

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pj = metapensiero.pj.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - dukpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - metapensiero.pj
  commands:
    - pj --help

about:
  home: https://gitlab.com/metapensiero/metapensiero.pj
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Javascript for refined palates: a Python 3 to ES6 Javascript translator.'

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
